[workspace]
members = ["programs/*"]
[profile.test]
overflow-checks = false

# [profile.release]
# lto = "fat"
# codegen-units = 1
# overflow-checks = false

# [profile.release.build-override]
# opt-level = 3
# incremental = false
# codegen-units = 1
