name: Lint project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  solana_version: 1.18.12
  anchor_version: 0.20.1

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install global mocha
        run: |
          npm install -g mocha
          npm install -g ts-mocha
          npm install -g typescript
          npm install -g @project-serum/anchor
          ts-mocha -h
      - name: install sdk
        run: |
          npm install
        working-directory: ./sdk
      - name: install
        run: |
          npm install
      - name: Trunk Check
        uses: trunk-io/trunk-action@v0.3.0-beta
